name:                scatM
version:             0.1.0.0
github:              "githubuser/scatM"
license:             BSD3
author:              "Grachkov A.A."
maintainer:          "leshaagrachkov@gmail.com"
copyright:           "2020 Alexey Grachkov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/scatM#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- typed-process
- process
- haskore
- text
- hvega
- split
- binary
- directory
- massiv
- word24

library:
  source-dirs: src

executables:
  scatM-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scatM

tests:
  scatM-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scatM
